title: Where Did You Get In?
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6341262550558895
  brandStrength: 0.252608569804579
  rhythmicContrast: 0.6118218582123518
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.8972043350804597
cta:
  bucket: null
  version: null
  domain: null
name: Where Did You Get In?
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.198174
layout_spectrum: 0
