name: Where Did You Get In?
favicon: null
layout_spectrum: 0.01468
typography_spectrum: 0.24168
title: Where Did You Get In?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.252608569804579
  lightness: 0.8972043350804597
  saturation: 0.6341262550558895
  rhythmicContrast: 0.6118218582123518
purpose: []
